### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Itsusinn** [Itsusinn/tuic#1]
- [x] Improve Mutex lock
- [x] Update to rustls v0.23
- [x] Refactor logging into async-friendly tracing. Blocked by android

And there are many interesting PRs could be merged

- [x] More CI targets https://github.com/EAimTY/tuic/pull/219
- [x] Skip cert verify https://github.com/EAimTY/tuic/pull/245
- [x] Docker CI https://github.com/EAimTY/tuic/pull/254

Some bugfixes
............

**Comment by Itsusinn** [comment]
> Client access to ipv6 service endpoint not working
> The debug log doesn't see the printout about [Relay]
> [socks] will print the TCP timeout

tuic-client + tuic-server？（not clash meta or singbox？）

IPv6 service meaning？
IPv6 tuic server？ or IPv6 traffic？

**Comment by Itsusinn** [comment]
@Fhokud Try https://github.com/Itsusinn/tuic/releases/tag/latest
It might (or mightn't) solve the problem
